### ISSUE TITLE
get_class() expects parameter 1 to be object, string given

### ISSUE THREAD

**Issue by mpjraaij** [clue/reactphp-block#36]
Hi there,

I am getting this error code:

```
PHP Warning:  get_class() expects parameter 1 to be object, string given in /phalcon/vendor/clue/block-react/src/functions.php on line 90
PHP Fatal error:  Uncaught UnexpectedValueException: Promise rejected with unexpected value of type  in /phalcon/vendor/clue/block-react/src/functions.php:89
Stack trace:
#0 /phalcon/vendor/clue/block-react/src/functions.php(198): Clue\React\Block\await(NULL, Object(React\EventLoop\StreamSelectLoop), NULL)
#1 /phalcon/app/tasks/RunTask.php(96): Clue\React\Block\awaitAll(NULL, Object(React\EventLoop\StreamSelectLoop))
```

I'm building my promises with the following code:

```php
$promises[] = $this->getTrades($rule->id, $exchange->id)
                    ->then(
                        function ($trades) use ($handleTrades) {
                            foreach ($trades as $trade) {
                                $handleTrades[] = $trade;
                            }
                        }
                    );
```

The function is like this:

```php
    private function getTrades($rule, $exchange) {
        $deferred = new React\Promise\Deferred();

        //...

        if (empty($trades->count())) {
            $deferred->reject("No trades found for rule $rule");
        } else {
            $deferred->resolve($trades);
        }

        return $deferred->promise();
    }
```

How do I solve this?

**Comment by Furgas** [comment]
Added a pull request for a `get_class` warning issue. As for your actual problem, I've answered on [Stackoverflow](https://stackoverflow.com/a/51498793/170403).

**Comment by clue** [comment]
@mpjraaij Thank you for reporting! This is indeed a small bug in this library, @Furgas has just filed PR #37 to fix this :+1: 

That being said, this only happens if you reject a promise with a scalar value instead of a an `Exception`. There's ongoing discussion to enforce `Exception` objects in the future, so I suppose it's a good idea to update your code to use an `Exception` just in case: https://github.com/reactphp/promise/issues/46
